### PR TITLE
[Modal] Tears down mutation observer on modal destruction

### LINKED ISSUE #6832: [Modal] destroy should tear down mutation observer
### Steps

- Show a modal with `{observeChanges: true}`
- Hide the modal (either programmatically or by, e.g. clicking on the dimmer)
- Some DOM updates are performed during the hide/destruction phase of the modal

### Expected Result

Scroll lock is removed from the dimmer root

### Actual Result

Scroll lock is incorrectly reinstated after tear down of the modal

### Version
2.4.0

### Testcase

The test case is quite tricky to extract as the specific problem I'm facing is caused by the interaction of Angular and the teardown mechanism of the modal. I can make a PR that fixes the behaviour as I have patched my local version to achieve the correct result.

### PR DESCRIPTION
**Pull request by euangoddard**
Fixes #6832

### CODE REVIEW

File: src/definitions/modules/modal.js [hunk 1]
```diff
@@ -138,6 +138,9 @@ $.fn.modal = function(parameters) {
         },
 
         destroy: function() {
+          if (module.observer) {
```
Comment (lubber-de) [inline src/definitions/modules/modal.js]: `if (observer)` should do it alone, because this variable is already declared here https://github.com/Semantic-Org/Semantic-UI/blob/0a42dcdcb400d6fc275b04d6cb052a48efd68536/src/definitions/modules/modal.js#L79

File: src/definitions/modules/modal.js [hunk 2]
```diff
@@ -160,6 +163,7 @@ $.fn.modal = function(parameters) {
               subtree   : true
             });
             module.debug('Setting up mutation observer', observer);
+            module.observer = observer;
```
Comment (lubber-de) [inline src/definitions/modules/modal.js]: As mentioned above, `observer` is already declared as private module variable and set by https://github.com/Semantic-Org/Semantic-UI/blob/0a42dcdcb400d6fc275b04d6cb052a48efd68536/src/definitions/modules/modal.js#L157, so this line should not be necessary

**Comment by euangoddard** [comment]
@lubber-de thanks for the feedback - I'd missed that declaration and have changed in line with your suggestion

**Comment by jlukic** [comment]
This looks good to merge.
